#!/bin/bash
set -e

UNZIP_OPTS=-qqu

# create and populate data dir

if [ -z $1 ] ; then
DATA_DIR=`pwd`/data
else
DATA_DIR=$1
fi

mkdir -p $DATA_DIR/
mkdir -p $DATA_DIR/world_boundaries
mkdir -p $DATA_DIR/simplified-land-polygons-complete-3857
mkdir -p $DATA_DIR/ne_110m_admin_0_boundary_lines_land
mkdir -p $DATA_DIR/ne_10m_populated_places
mkdir -p $DATA_DIR/land-polygons-split-3857

# world_boundaries
echo "dowloading world_boundaries..."
curl -z "$DATA_DIR/world_boundaries-spherical.tgz" -L -o "$DATA_DIR/world_boundaries-spherical.tgz" "http://planet.openstreetmap.org/historical-shapefiles/world_boundaries-spherical.tgz"
echo "expanding world_boundaries..."
tar -xzf $DATA_DIR/world_boundaries-spherical.tgz -C $DATA_DIR/

# simplified-land-polygons-complete-3857
echo "downloading simplified-land-polygons-complete-3857..."
curl -z "$DATA_DIR/simplified-land-polygons-complete-3857.zip" -L -o "$DATA_DIR/simplified-land-polygons-complete-3857.zip" "http://data.openstreetmapdata.com/simplified-land-polygons-complete-3857.zip"
echo "simplified-land-polygons-complete-3857..."
unzip $UNZIP_OPTS $DATA_DIR/simplified-land-polygons-complete-3857.zip simplified-land-polygons-complete-3857/simplified_land_polygons.{shp,shx,prj,dbf,cpg} -d $DATA_DIR/

# ne_110m_admin_0_boundary_lines_land
echo "dowloading ne_110m_admin_0_boundary_lines_land..."
curl -z $DATA_DIR/ne_110m_admin_0_boundary_lines_land.zip -L -o $DATA_DIR/ne_110m_admin_0_boundary_lines_land.zip http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip
echo "expanding ne_110m_admin_0_boundary_lines_land..."
unzip $UNZIP_OPTS $DATA_DIR/ne_110m_admin_0_boundary_lines_land.zip -d $DATA_DIR/ne_110m_admin_0_boundary_lines_land/

# ne_10m_populated_places
echo "dowloading ne_10m_populated_places..."
curl -z $DATA_DIR/ne_10m_populated_places.zip -L -o $DATA_DIR/ne_10m_populated_places.zip http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_populated_places.zip
echo "expanding ne_10m_populated_places..."
unzip $UNZIP_OPTS $DATA_DIR/ne_10m_populated_places.zip -d $DATA_DIR/ne_10m_populated_places/

# land-polygons-split-3857
echo "dowloading land-polygons-split-3857..."
curl -z "$DATA_DIR/land-polygons-split-3857.zip" -L -o "$DATA_DIR/land-polygons-split-3857.zip" "http://data.openstreetmapdata.com/land-polygons-split-3857.zip"
echo "expanding land-polygons-split-3857..."
unzip $UNZIP_OPTS $DATA_DIR/land-polygons-split-3857.zip -d $DATA_DIR/


#process populated places
echo "processing ne_10m_populated_places..."
rm -f $DATA_DIR/ne_10m_populated_places/ne_10m_populated_places_fixed.*
ogr2ogr $DATA_DIR/ne_10m_populated_places/ne_10m_populated_places_fixed.shp $DATA_DIR/ne_10m_populated_places/ne_10m_populated_places.shp

#index
echo "indexing shapefiles"

shapeindex --shape_files \
$DATA_DIR/simplified-land-polygons-complete-3857/simplified_land_polygons.shp \
$DATA_DIR/land-polygons-split-3857/land_polygons.shp \
$DATA_DIR/ne_10m_populated_places/ne_10m_populated_places_fixed.shp \
$DATA_DIR/ne_110m_admin_0_boundary_lines_land/ne_110m_admin_0_boundary_lines_land.shp


#clean up
echo "cleaning up..."
rm $DATA_DIR/ne_10m_populated_places/ne_10m_populated_places.*

echo "...done!"
